import { createApp } from 'vue';
import { createPinia } from 'pinia';
import router from './router';
import App from './App.vue';
import 'vant/lib/index.css';
import { Button, Form, Field, CellGroup, Toast, Notify, NavBar, Swipe, SwipeItem, Grid, GridItem, Tabbar, TabbarItem, Image as VanImage, Popup, DatePicker, Dialog, Sidebar, SidebarItem, Card, SubmitBar, ActionSheet, Stepper, Tag, Icon, Badge, TreeSelect, RadioGroup, Radio, Tabs, Tab, AddressList, TimePicker, Cell, Search, FloatingBubble, ConfigProvider, Picker, Loading, AddressEdit, Uploader, Switch, SwipeCell, PullRefresh, Empty, Checkbox, CheckboxGroup, Cascader, Area } from 'vant';
import '@vant/touch-emulator';
import '../styles/main.css';
import { useThemeStore } from './store/theme';

const app = createApp(App);
app.use(createPinia());
const theme = useThemeStore();
theme.init();
app.use(router);
app.use(Button);
app.use(Form);
app.use(Field);
app.use(CellGroup);
app.use(Toast);
app.use(Notify);
app.use(NavBar);
app.use(Swipe);
app.use(SwipeItem);
app.use(Grid);
app.use(GridItem);
app.use(Tabbar);
app.use(TabbarItem);
app.use(VanImage);
app.use(Popup);
app.use(DatePicker);
app.use(Dialog);
app.use(Sidebar);
app.use(SidebarItem);
app.use(Card);
app.use(SubmitBar);
app.use(ActionSheet);
app.use(Stepper);
app.use(Tag);
app.use(Icon);
app.use(Badge);
app.use(TreeSelect);
app.use(RadioGroup);
app.use(Radio);
app.use(Tabs);
app.use(Tab);
app.use(AddressList);
app.use(TimePicker);
app.use(Cell);
app.use(Search);
app.use(FloatingBubble);
app.use(ConfigProvider);
app.use(Picker);
app.use(Loading);
app.use(AddressEdit);
app.use(Uploader);
app.use(Switch);
app.use(SwipeCell);
app.use(PullRefresh);
app.use(Empty);
app.use(Checkbox);
app.use(CheckboxGroup);
app.use(Cascader);
app.use(Area);
app.mount('#app');
